Assignment 1 (due on 10/29)  
学生：张彬彬 (12532747)
批改人：Hubeihui 
得分：(95/100)

第一题，-2分，题目部分理解错误，已经改正代码。

In [ ]:
#ese5023 ps1 report ( think myself first and get help from gemini )比大小
a = 5
b = 15
c = 10
#定义函数def
def calculate_and_print(x, y, z):
    result = x + y - 10 * z
    #AI help:重点f，另有：
    #1： +连接： print(" 计算: " + str(x) + " + " + str(y) + " - 10 * " + str(z) + " = " + str(result))
    #2： .format() 方法： print(" 计算: {} + {} - 10 * {} = {}".format(x, y, z, result))
    print(f"  计算: {x} + {y} - 10 * {z} = {result}")
def  Print_values(a,b,c):
    #右侧命令框，注意下面if需要在def下缩进一格
    if a>b :
        if b > c:
            #a>b>c; and learn the step after print with AI
            print("a,b,c")
            calculate_and_print(a,b,c)
            #break :code run row by row if this is run,the code would stop
        else:
            if a > c:
                print("a,c,b")
                calculate_and_print(a,c,b)
            else:
                print("c,a,b")
                calculate_and_print(c,a,b)
    #左侧b>a
    else:    
         if b > c:
            ## 助教：这里只需要输出blank就行
            print("there have nothing")
         else:
            print("c,b,a")
            calculate_and_print(c,b,a)
#print(result)，这步需要函数执行
#print(f"{result}")为什么会错误？
Print_values(a,b,c)


there have nothing


第二题，方法正确，但不需要输出最大值。你的方法使用了动态规划算法，这比递归方法更稳定。

In [8]:
#work 2 Continuous celing function ( think myself first and get help from gemini )递归
#ask AI 'what is celing'.=>进一法；Recursion
#导入math，才能使用ceil函数; 
#在 Python 中，f(i) 这种写法的意思是“调用一个叫做 f 的函数，并把 i 作为参数传给它”。但你其实是想创建一个变量来存储一个值。
import math
#创建列表
input_list = [1,3,4,6,46,78,35]
#print(max)
#列表是否为空
#if input_list = []:
if not input_list :
    print("输入列表为空，程序结束")
else:
    #max_val = max(input_list) 本身是完全正确的。问题出在你之前运行过的代码“污染”了 max 这个名字。可以重启内核
    max_val = max(input_list)
    #f(1)=1
    f_results = {1 : 1}
    print(f"需要输出的max值：{max_val}")
    #算最大里面含有其他比它小的数的答案
    for i in range (2 , max_val + 1):
        f_i_index = math.ceil(i/3)
        
        process_value = f_results[f_i_index]

        F_i = process_value + 2 * i

        f_results[i] = F_i
    print("最大值以及过程值运算完成")    

    F_x = []

    for number in input_list:
        f_x = f_results[number]
        F_x.append(f_x)

    print("结果")
    print(f"输入的列表：{input_list}")
    print(f"计算的结果：{F_x}")


需要输出的max值：78
最大值以及过程值运算完成
结果
输入的列表：[1, 3, 4, 6, 46, 78, 35]
计算的结果：[1, 7, 13, 17, 141, 233, 107]


第3题，输出正确，但是代码结构不是很“优雅”，实际上，你定义的是solve_dice_problem函数，题目要求定义一个Find_number_of_ways 函数来计算，而你的代码中，Find_number_of_ways 只是solve_dice_problem的子函数。帮你改进了代码结构。

In [12]:
#work 3 Dice（骰子） rolling ( think myself first and get help from gemini )
#dp方法 vs 矩阵：dp方法复杂度低，更优雅
def Find_number_of_ways(x):
    #骰子个数以及点数
    n_dice  = 10
    n_score = 6
    #可能的最大数
    max_sum_maybe = n_dice * n_score
    #列表推导式，创建我们需要的二维 DP 表；_可以无需输入数而是直接引用
    dp = [[0] * (max_sum_maybe + 1) for _ in range(n_dice +1)]        
    #基本定义计算次数
    dp[0][0] = 1
    #开始遍历所有可能，同时在做题时注意要补充j=>骰子个数
    #all dice number
    for i in range(1 , n_dice +1 ):
        #all dice and all sum maybe score，易出错
        for j in range (1 , max_sum_maybe + 1 ):
            #all single dice score
            for z in range (1 , n_score + 1 ):
                #>= right , => error
                if j >= z :
                    #plus and sum
                    dp[i][j] += dp[i-1][j-z]

    #可能点数要大于dice number,don't forget ':'
    if not (n_dice <= x <= max_sum_maybe):
        return 0
    return dp[n_dice][x]
    #输出检查
print(f"10个骰子和为 10 的方法数: {Find_number_of_ways(10)}")
print(f"10个骰子和为 35 的方法数: {Find_number_of_ways(35)}")
print(f"10个骰子和为 60 的方法数: {Find_number_of_ways(60)}")
# 测试一个无效输入
print(f"10个骰子和为 7 的方法数: {Find_number_of_ways(7)}")


10个骰子和为 10 的方法数: 1
10个骰子和为 35 的方法数: 4395456
10个骰子和为 60 的方法数: 1
10个骰子和为 7 的方法数: 0


In [ ]:
3.1 #助教：我把与3.1重复的代码删了，以后可以不重复写，你前面的运行过，后面的代码块就可以接着用前面的函数的。
Number_of_ways = []
#数学上x =[10,60]，编程右侧+1,notice the step would make list star from 1(its place) not 10(i think)
all_x_range = range(10 , 60 +1 )
for x in all_x_range:
    ways = Find_number_of_ways(x)
    #放置数字在列表最后端，记录外加查找
    Number_of_ways.append(ways)
#set max_index to find.remember add 10 
max_ways  = max(Number_of_ways)
max_index = Number_of_ways.index(max_ways)
#recover the place to i think(start from 10)
x_max_ways = 10 + max_index
#check the results
print(f"x 从 10 到 60 的方法数列表 (Number_of_ways):")
print(f"\n完整的方法数列表 (从x=10到x=60):\n{Number_of_ways}")
#print(f"10个骰子和为 {all_x_range} 的方法数: {Find_number_of_ways(x)}")，这一列跳出循环，不会得到我想要的结果
print(f"  列表中的最大方法数为: {max_ways}")
print(f"  产生这个最大方法数的 x 值是: {x_max_ways}")
#定义函数后应该调用它来运行
# solve_dice_problem()


x 从 10 到 60 的方法数列表 (Number_of_ways):

完整的方法数列表 (从x=10到x=60):
[1, 10, 55, 220, 715, 2002, 4995, 11340, 23760, 46420, 85228, 147940, 243925, 383470, 576565, 831204, 1151370, 1535040, 1972630, 2446300, 2930455, 3393610, 3801535, 4121260, 4325310, 4395456, 4325310, 4121260, 3801535, 3393610, 2930455, 2446300, 1972630, 1535040, 1151370, 831204, 576565, 383470, 243925, 147940, 85228, 46420, 23760, 11340, 4995, 2002, 715, 220, 55, 10, 1]
  列表中的最大方法数为: 4395456
  产生这个最大方法数的 x 值是: 35


第4题，4.3没有绘图，-3分。

In [6]:
#work 4 Dynamic programming ( think myself first and get help from gemini )
#4.1
import random

def Random_integer(N):
    #  0 到 10 之间（包含 0 和 10）随机选取的整数
    return [random.randint(0, 10) for _ in range(N)]   
    #print(f"{Random_integer(N)}"),return后面的代码会无法运行
#检查运行
list_size = 5
generated_list = Random_integer(list_size)
print(f" {list_size} 个随机数的列表是: {generated_list}")


 5 个随机数的列表是: [1, 6, 8, 9, 6]


In [16]:
#work 4 Dynamic programming ( think myself first and get help from gemini )
import random

def Random_integer(N):
    #  0 到 10 之间（包含 0 和 10）随机选取的整数
    return [random.randint(0, 10) for _ in range(N)]   
#4.2
def Sum_averages(arr):
    N = len(arr)#看列表有多少元素
    if N == 0:
        return 0
    arr_sum = sum(arr)
    #计算2的N次方：pow(2,N)
    pow_2_N = pow(2,N)
    total = arr_sum * (pow_2_N - 1) / N
    return total

In [17]:
#work 4 Dynamic programming ( think myself first and get help from gemini )
#4.3
#
if __name__ == "__main__":
    
    # 初始化一个列表来存储 N 从 1 到 100 的所有 Sum_averages 结果
    Total_sum_averages = []
    
    # 1 到 100（包含 100）
    N_range = range(1, 101)
    
    print(" N 从 1 到 100 的：")
    
    # 循环 N
    for N in N_range:
        # 4.1: 生成一个随机数组
        random_array = Random_integer(N)
        
        # 4.2: 计算该数组的子集平均值之和
        current_sum = Sum_averages(random_array)
        
        # 将结果添加到我们的总列表中
        Total_sum_averages.append(current_sum)
        
    for i in range(100):
        print(f"  N = {i+1}: {Total_sum_averages[i]:.2f}")    
    #文字说明
    print("这是一个指数函数，说明需要其他的方法减少计算量，不然面对太多元素的时候容易让电脑无法快速运行")



 N 从 1 到 100 的：
  N = 1: 2.00
  N = 2: 18.00
  N = 3: 44.33
  N = 4: 41.25
  N = 5: 167.40
  N = 6: 283.50
  N = 7: 417.29
  N = 8: 1816.88
  N = 9: 2441.44
  N = 10: 6035.70
  N = 11: 10793.27
  N = 12: 19792.50
  N = 13: 39694.85
  N = 14: 85425.64
  N = 15: 168203.93
  N = 16: 253948.12
  N = 17: 570544.35
  N = 18: 1106826.00
  N = 19: 2649029.05
  N = 20: 6710880.00
  N = 21: 11983720.00
  N = 22: 22878016.36
  N = 23: 45225533.39
  N = 24: 89478480.00
  N = 25: 161061268.80
  N = 26: 374260966.73
  N = 27: 666117608.07
  N = 28: 1370938216.61
  N = 29: 2684354555.00
  N = 30: 5368709115.00
  N = 31: 10391049904.84
  N = 32: 20937965563.12
  N = 33: 39305458280.03
  N = 34: 89941668075.71
  N = 35: 178670639508.40
  N = 36: 282513404355.00
  N = 37: 794917190345.78
  N = 38: 1519062117316.58
  N = 39: 2932031007397.33
  N = 40: 5305143604014.38
  N = 41: 12765061824905.80
  N = 42: 22723240307365.50
  N = 43: 45412387230929.16
  N = 44: 87960930222075.00
  N = 45: 175921860444155.

第5题都对，为了简洁，也删除了重复的代码。

In [9]:
#work 5 Path counting ( think myself first and get help from gemini )
#5.1
#get ready to set np
import numpy as np
N = 10  # 行数
M = 8   # 列数
#创建矩阵，先行后列
def create_matrix(N,M):
    matrix = np.random.randint(0 , 2 ,size=(N,M),dtype=int)
    #初始点左上角以及终点必为一
    matrix[0,0] = 1
    matrix[N-1,M-1] = 1
    return matrix
#检查运行
generated_matrix = create_matrix(N, M)
print(f"生成的矩阵是: \n{generated_matrix}")



生成的矩阵是: 
[[1 0 1 1 0 0 0 0]
 [1 0 0 1 0 1 1 0]
 [1 1 0 1 1 1 1 0]
 [0 0 1 0 1 0 0 1]
 [1 1 1 0 0 0 0 0]
 [1 0 1 0 1 1 1 1]
 [0 1 1 0 1 0 1 0]
 [1 0 1 1 1 0 1 0]
 [1 0 1 1 1 0 1 0]
 [0 0 0 0 1 1 1 1]]


In [18]:
#work 5 Path counting ( think myself first and get help from gemini )
import numpy as np
N = 10  # 行数 
M = 8  # 列数
#创建矩阵，先行后列
def create_matrix(N,M):
    matrix = np.random.randint(0 , 2 ,size=(N,M),dtype=int)
    #初始点左上角以及终点必为一
    matrix[0,0] = 1
    matrix[N-1,M-1] = 1
    return matrix

#5.2
def Count_path(matrix):
    N,M = matrix.shape
    #creat dynamic matrix
    dp = np.zeros((N,M),dtype = int)
    #at the start
    dp[0, 0] = 1
    #only down
    for i in range(1,N):
        #only 1 can run
        if matrix[i,0] == 1:
            dp[i,0] = dp[i - 1 ,0]   
    #left run
    for j in range(1,M):
        #only 1 can run
        if matrix[0,j] == 1:
            dp[0,j] = dp[0,j - 1]

    #run other area
    for i in range(1,N):        
        for j in range(1,M):
            if matrix[i,j] == 1:
                dp[i,j] = dp[i-1,j] + dp[i,j-1]
    return dp[N-1,M-1]
#检查
generated_matrix = create_matrix(N, M)
print(f"生成的 {N}x{M} 矩阵是:\n{generated_matrix}")
total_paths = Count_path(generated_matrix)
print(f"从左上角到右下角的路径总数是: {total_paths}")


生成的 10x8 矩阵是:
[[1 0 0 1 1 0 1 0]
 [1 0 1 0 0 1 1 0]
 [0 1 0 0 0 0 0 0]
 [1 1 0 0 1 0 0 0]
 [0 1 1 0 1 0 0 0]
 [0 1 1 0 0 1 0 1]
 [0 0 0 1 1 1 1 0]
 [1 1 0 0 0 0 0 0]
 [0 0 1 1 1 0 1 1]
 [1 1 1 0 1 0 0 1]]
从左上角到右下角的路径总数是: 0


c:\Users\lenovo\anaconda3\envs\ese5023\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\lenovo\anaconda3\envs\ese5023\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
c:\Users\lenovo\anaconda3\envs\ese5023\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [25]:
#work 5 Path counting ( think myself first and get help from gemini )
import numpy as np
N = 10  # 行数 
M = 8  # 列数
#5.3
if __name__ == "__main__":
    num_runs = 1000  # 模拟次数
    # 初始化总路径数
    total_paths = 0
    print(f"开始 {num_runs} 次路径计算...")
    print(f"矩阵大小: N={N}, M={M}")
    # 循环
    for i in range(num_runs):
        random_matrix = create_matrix(N, M)
        paths_count = Count_path(random_matrix)
        total_paths += paths_count
    # 计算平均
    mean_paths = total_paths / num_runs
    # 结果
    print(f"累计找到的总路径数: {total_paths}")
    print(f"平均路径数: {mean_paths:.2f}") # 2f ：保留两位小数

开始 1000 次路径计算...
矩阵大小: N=10, M=8
累计找到的总路径数: 469
平均路径数: 0.47
